services:
  tests:
    build:
      context: ..
      dockerfile: environment_builder/Dockerfile
    image: saucedemo:latest
    working_dir: /app
    command: ["tests/fe"]
    environment:
      - HEADLESS=true
    env_file:
      - .env
    volumes:
      - ../automation_framework/reports:/app/automation_framework/reports
      - ../automation_framework/logs:/app/automation_framework/logs
