version: "3.8"

services:
  tests:
    build: .
    image: saucedemo:latest
    working_dir: /app
    environment:
      - HEADLESS=0
    env_file:
      - .env
    volumes:
      - ./automation_framework/reports:/app/automation_framework/reports
      - ./automation_framework/logs:/app/automation_framework/logs
    command: ["pytest", "-c", "automation_framework/pytest.ini"]
