name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file
      run: |
        cat << EOF > environment_builder/.env
        SAUCE_DEMO_URL=https://www.saucedemo.com/
        STANDART_USERNAME=standard_user
        LOCKED_OUT_USERNAME=locked_out_user
        PROBLEM_USERNAME=problem_user
        PERFORMANCE_GLITCH_USERNAME=performance_glitch_user
        ERROR_USERNAME=error_user
        VISUAL_USERNAME=visual_user
        PASSWORD=secret_sauce
        HEADLESS=true
        PW_TRACE=on-failure
        DB_HOST=192.168.000.00
        DEV_NODE=Test
        DB_PORT=3036
        DB_USERNAME=admin
        DB_PASSWORD=root
        EOF

    - name: Run tests with Docker Compose
      run: |
        cd environment_builder
        docker compose up --build --abort-on-container-exit

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: automation_framework/reports/allure-results/

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-report
        path: automation_framework/reports/html-report/

    - name: Upload Playwright Traces
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-traces
        path: automation_framework/reports/playwright-traces/

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs
        path: automation_framework/logs/
